Move overlay[s].nix files outside of the nix subdir.
@noteed I /think/ this will be needed since nix chokes on referencing
parent dirs. If we have overlay.nix in ./nix; we'll need to reference
./default.nix, which is in the parent dir.

Now, to be able to use start-servant as a dependency, the depending
package needs to overlay haskellPackages with start servant like so:

```
let

  sources = import ./sources.nix;
  start-servant = import sources.start-servant;

  # We can overlay haskell packages here: this is the source of our troubles.
  haskellOverlays = [ "${start-servant}/nix/overlay.nix" ];

in haskellOverlays ++ [ (import ./overlay.nix) ]
```

Which fails with a rather unhelpful nix error:

```
╰─$ nix-shell --show-trace                                                                                                                                             130 ↵
error: while evaluating anonymous function at /nix/store/18dc5zlm6ginhh0kpra887gy0x4b6g2w-nixpkgs-src/pkgs/top-level/impure.nix:15:1, called from /mnt/1tb/code/smart/prototype-hs/shell.nix:7:23:
while evaluating anonymous function at /nix/store/18dc5zlm6ginhh0kpra887gy0x4b6g2w-nixpkgs-src/pkgs/top-level/default.nix:20:1, called from /nix/store/18dc5zlm6ginhh0kpra887gy0x4b6g2w-nixpkgs-src/pkgs/top-level/impure.nix:84:1:
while evaluating anonymous function at /nix/store/18dc5zlm6ginhh0kpra887gy0x4b6g2w-nixpkgs-src/pkgs/stdenv/booter.nix:42:1, called from /nix/store/18dc5zlm6ginhh0kpra887gy0x4b6g2w-nixpkgs-src/pkgs/top-level/default.nix:123:10:
while evaluating 'dfold' at /nix/store/18dc5zlm6ginhh0kpra887gy0x4b6g2w-nixpkgs-src/pkgs/stdenv/booter.nix:60:27, called from /nix/store/18dc5zlm6ginhh0kpra887gy0x4b6g2w-nixpkgs-src/pkgs/stdenv/booter.nix:136:4:
while evaluating 'go' at /nix/store/18dc5zlm6ginhh0kpra887gy0x4b6g2w-nixpkgs-src/pkgs/stdenv/booter.nix:63:18, called from /nix/store/18dc5zlm6ginhh0kpra887gy0x4b6g2w-nixpkgs-src/pkgs/stdenv/booter.nix:72:13:
while evaluating 'folder' at /nix/store/18dc5zlm6ginhh0kpra887gy0x4b6g2w-nixpkgs-src/pkgs/stdenv/booter.nix:89:33, called from /nix/store/18dc5zlm6ginhh0kpra887gy0x4b6g2w-nixpkgs-src/pkgs/stdenv/booter.nix:68:18:
while evaluating 'allPackages' at /nix/store/18dc5zlm6ginhh0kpra887gy0x4b6g2w-nixpkgs-src/pkgs/top-level/default.nix:113:17, called from /nix/store/18dc5zlm6ginhh0kpra887gy0x4b6g2w-nixpkgs-src/pkgs/stdenv/booter.nix:101:12:
while evaluating anonymous function at /nix/store/18dc5zlm6ginhh0kpra887gy0x4b6g2w-nixpkgs-src/pkgs/top-level/stage.nix:12:1, called from /nix/store/18dc5zlm6ginhh0kpra887gy0x4b6g2w-nixpkgs-src/pkgs/top-level/default.nix:113:26:
while evaluating 'fix' at /nix/store/18dc5zlm6ginhh0kpra887gy0x4b6g2w-nixpkgs-src/lib/fixed-points.nix:19:9, called from /nix/store/18dc5zlm6ginhh0kpra887gy0x4b6g2w-nixpkgs-src/pkgs/top-level/stage.nix:248:3:
while evaluating 'extends' at /nix/store/18dc5zlm6ginhh0kpra887gy0x4b6g2w-nixpkgs-src/lib/fixed-points.nix:69:24, called from /nix/store/18dc5zlm6ginhh0kpra887gy0x4b6g2w-nixpkgs-src/lib/fixed-points.nix:19:20:
while evaluating 'extends' at /nix/store/18dc5zlm6ginhh0kpra887gy0x4b6g2w-nixpkgs-src/lib/fixed-points.nix:69:24, called from /nix/store/18dc5zlm6ginhh0kpra887gy0x4b6g2w-nixpkgs-src/lib/fixed-points.nix:69:42:
while evaluating 'extends' at /nix/store/18dc5zlm6ginhh0kpra887gy0x4b6g2w-nixpkgs-src/lib/fixed-points.nix:69:24, called from /nix/store/18dc5zlm6ginhh0kpra887gy0x4b6g2w-nixpkgs-src/lib/fixed-points.nix:69:42:
opening file '/nix/store/yrd74scd6zvqavrawcfcdz5dcpl3fgrn-source/default.nix': No such file or directory
```

Which I suspect is because of parent directory traversals/references (I've seen
something like this earlier, in the wild).