Checkpoint commit: possible GHC bug?
This doesn't compile for no obvious reason:

```

src/Prototype/Server/New.hs:6:51: error:
    Module ‘Prototype.Server.New.StartPage’ does not export ‘Protected’
  |
6 | import           Prototype.Server.New.StartPage ( Protected )
  |                                                   ^^^^^^^^^
cabal: Failed to build start-servant-0.1.0.0 (which is required by
exe:start-servant from start-servant-0.1.0.0).

```

Although this type is being exported by the module. I've cleared all
build artefacts but I've not been able to get rid of this error.